### ISSUE TITLE
http can not be updated because of the 'betamax' package

### ISSUE THREAD

**Issue by ninogjoni** [nhost/nhost-dart#110]
In my current pull request, I attempted to update the 'http' package to version 1.1.0.
However, the 'betamax' package relies on an older version of 'http', and it seems that it might not be maintained any longer (the last update was approximately 17 months ago).

If I don't receive a response, how can we address this?

**Comment by ninogjoni** [comment]
Here the issue [link](https://github.com/shyndman/betamax/issues/5)

**Comment by sgruhier** [comment]
With http: 0.13.4 we are stuck on upgrade. latest version of flutter uses http: 1+
This is now critical :(

**Comment by totzk9** [comment]
Isn't it a better practice to not use as many package as possible? There are ways to test endpoints without using other packages like `betamax`

**Comment by mhadaily** [comment]
I agree with @totzk9 , this package was here as the author of betamax used to be the maintainer of this repo. However, I should consider removing this package and try to implement things without unnecessary dependencies. 

PR is welcome.

**Comment by sgruhier** [comment]
I understand that people cannot stay maintainer for life. But being blocked to an old flutter version because that it's a shame. I'm considering not using nhost anymore to avoid this kind of situation. betamax isn't maintained since 2017! I don't even understand why it has been used :)

**Comment by dbarrosop** [comment]
Solved in #119
