### ISSUE TITLE
[nhost_graphql_adapter] bump http ^0.13.5 dependency

### ISSUE THREAD

**Issue by marcusrohden** [nhost/nhost-dart#116]
Hey guys,

I'm not able to update some of my dependencies due to _nhost_graphql_adapter_ requiring _http ^0.13.5_ .
The current http version is 1.1.0

Could you please upgrade the dependencies from the package?

Thank you!!!

**Comment by onehassan** [comment]
fixed in https://github.com/nhost/nhost-dart/pull/119
