### ISSUE TITLE
dependencies issue

### ISSUE THREAD

**Issue by zaqwery** [nhost/nhost-dart#130]
hi, 

I'm trying to resolve this while upgrading uuid to latest 4.3.2 but getting this issue with nhost_dart:

```
Because no versions of nhost_dart match >2.0.1 <3.0.0 and nhost_dart 2.0.1 depends on nhost_graphql_adapter ^4.0.1, nhost_dart ^2.0.1 requires nhost_graphql_adapter ^4.0.1.
And because no versions of nhost_graphql_adapter match >4.0.1 <5.0.0 and nhost_graphql_adapter 4.0.1 depends on nhost_gql_links ^4.0.1, nhost_dart ^2.0.1 requires nhost_gql_links ^4.0.1.
And because no versions of nhost_gql_links match >4.0.1 <5.0.0 and nhost_gql_links 4.0.1 depends on gql_websocket_link ^1.1.0, nhost_dart ^2.0.1 requires gql_websocket_link ^1.1.0.
Because gql_websocket_link 1.1.0 depends on uuid ^3.0.1 and no versions of gql_websocket_link match >1.1.0 <2.0.0, gql_websocket_link ^1.1.0 requires uuid ^3.0.1.
Thus, nhost_dart ^2.0.1 requires uuid ^3.0.1.
So, because 123_app depends on both nhost_dart ^2.0.1 and uuid ^4.3.2, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on uuid: flutter pub add uuid:^3.0.7
exit code 1
```

thoughts?

thanks!

**Comment by dbarrosop** [comment]
This is a dependency of our dependencies so we'd need to investigate which versions of those dependencies have the latest version of that package. If you want to take a look and open PR it will be most welcomed. Thanks!

**Comment by knaeckeKami** [comment]
Maintainer of gql-dart here.

It's gql_websocket_link link, which should be bumped to 2.0.0 (there was a change which is technically breaking, but should not affect most users https://github.com/gql-dart/gql/pull/418/files )

**Comment by dbarrosop** [comment]
Thanks a lot for the extra information!

**Comment by zaqwery** [comment]
Hi @onehassan , @dbarrosop 
upgraded your dependencies, please check out pr#132. 
Regards,

**Comment by onehassan** [comment]
fixed in https://github.com/nhost/nhost-dart/pull/132
