### ISSUE TITLE
How to use Hasura GQL subscription query?

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost-dart#134]
I need on how to use subscription query with the gql client i.e.

```gql
subscription($id:uuid!) {
  products_by_pk(id: $id){
   id
   title
  }
 }
```

I can see there is SubscriptionOption query but not sure what to provide for the document param, could provide an example for how to use the SubscriptionOption? 

thanks

**Comment by dbarrosop** [comment]
You can look at the example we have here: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_graphql/example

For instance, https://github.com/nhost/nhost-dart/blob/main/packages/nhost_flutter_graphql/example/lib/todos_quick_start_example.dart#L72

If you have further questions, please, don't use github issues, use a [discussion](https://github.com/nhost/nhost/discussions) or join our [discord](https://discord.com/invite/9V7Qb2U)
