### ISSUE TITLE
storage function uploadBytes  requires "name", but the column is nullable

### ISSUE THREAD

**Issue by marcusrohden** [nhost/nhost-dart#137]
hey guys,
I have just realised that the table "files" on storage has the column "name" set as nullable, but the uploading to storage function "uploadBytes" from the NHost dart library requires a not nullable string.

Is this intentional?

`Future<FileMetadata> uploadBytes({required String fileName, required List<int> fileContents, String? fileId, String? bucketId, String mimeType = applicationOctetStreamType, UploadProgressCallback? onUploadProgress});`

**Comment by dbarrosop** [comment]
Yes, that's on purpose as hasura-storage needs to be able to create an empty row to verify the user has permissions to upload files.

Closing as this is intentional and there is nothing to do.

**Comment by marcusrohden** [comment]
David, I mean, the library in flutter does not let it be optional. is that correct?

**Comment by dbarrosop** [comment]
The library is correct.

**Comment by dbarrosop** [comment]
Sorry, I responded too fast initially, I deleted my comment and commented in the PR instead.
