### ISSUE TITLE
Latest version does no longer work on Flutter Web

### ISSUE THREAD

**Issue by escamoteur** [nhost/nhost-dart#15]
Hi,

I got surprised this afternoon after a new deploy of the donation tracker suddenly no data at all got displayed. It works on Windows but not on web.

**Comment by shyndman** [comment]
Hi @escamoteur,

Do you have any more details? What does work mean?

**Comment by escamoteur** [comment]
it just doesn't return any data on the subscriptions. Not Error messages.

**Comment by escamoteur** [comment]
if you push the current state of the donation tracker you can see yourself I haven't yet pushed the version with the earlier versions again

**Comment by escamoteur** [comment]
Oh and the latest version still looses the subscription after a time

**Comment by shyndman** [comment]
OK, thanks. I'll take a look.

**Comment by shyndman** [comment]
Published two new package versions that solve the web issue. #16 provides more details about the issue.

```
nhost_gql_links       1.0.3
nhost_graphql_adapter 1.0.5
```

**Comment by shyndman** [comment]
Taking a look at donation tracker subscription issues now, which are presumably unrelated.
