### ISSUE TITLE
Return upload progress for fileupload

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost-dart#17]
It would be great to have a callback to retrieve the upload progress of a file, to show it back to users. Firebase offered a subscription method to the upload progress, which was very helpful and user friendly.

Thanks!

**Comment by shyndman** [comment]
This would definitely be a useful feature. We made the decision to use the `http` library for two reasons:

1. It's the same library used by `graphql`, meaning smaller binaries
2. It has first-class support for multipart HTTP requests, unlike the library in `dart:io`

Oddly, the library does not support progress (https://github.com/dart-lang/http/issues/465). 

That said, I'm sure this is possible with a some effort. I'm going to do some research and see what comes up.

**Comment by shyndman** [comment]
OK, I've looked into how this is implemented elsewhere, and replicating their approach is definitely possible. 

But it's unclear to me whether the approach I'm seeing in other libraries is right exactly, as they appear to be measuring the progress of data being written to the socket's buffer, and not the network.

But I think I see the piece they're missing. Definitely needs a bit of experimentation, but I think this can be done.

**Comment by shyndman** [comment]
@MaxSchilling, out of interest, can you provide me a rough estimate of the size of file your customers would be uploading?

**Comment by MaxSchilling** [comment]
We are uploading medium compressed videos, so roughly 3-10MB, maybe up to 20/50? But not more I think

**Comment by MaxSchilling** [comment]
Thanks for the research and the support! Not super urgent, but I think a nice convenient feature any way

**Comment by shyndman** [comment]
This has been implemented for awhile.
