### ISSUE TITLE
E-Mail Verification status as Authentication status

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost-dart#2]
It would be a great help to be able to make use of the e-mail verification status in the auth part as authentication status, or a bool attached to the current user would be a great help for the overall auth process.
Right now it seems there is only a way to read the ApiException message? Adding different status codes than 400 would help as well here in general.
Many thanks!

**Comment by shyndman** [comment]
I think this issue may also be useful to post on https://github.com/nhost/hasura-backend-plus/ (if we're talking about response codes), which is where all the backend logic lives.

Would you mind expanding a little bit...what would the `bool` indicate? I _believe_ the `nhost.auth.currentUser` should be `null` if you aren't authenticated (and if that isn't the case, let us know)

What kind of information do you want to pull out of the ApiException?

**Comment by MaxSchilling** [comment]
What I would like to have is actually
nhostClient.auth.currentUser == null --> No logged in user (check)
nhostClient.auth.currentUser != null --> User exists (available as well)
nhostClient.auth.currentUser.emailVerified --> true / false - Have this as a property for example to check if the email is already verified, to redirect to a "resend verification mail screen" or something and not let the user continue without the email being confirmed. So just another option to differentiate between existing users, that have or haven't confirmed their email yet.

**Comment by MaxSchilling** [comment]
Currently I only get this information from the message of the ApiException. 
And as that is just a string and may even change, that's pretty risky to implement a process like the email verification on.

**Comment by escamoteur** [comment]
@shyndman That was my question because its not part of the normal Hasura package for my understanding

**Comment by shyndman** [comment]
So did that answer your question? Email verification is not a part of Hasura.

**Comment by elitan** [comment]
Everything related to Auth is in [Hasura Backend Plus](https://github.com/nhost/hasura-backend-plus).

You can't log in from any client (ex Flutter) if the user is not active. 

You can see if a user is active by checking the `active` column in the `auth.accounts` table. Every user has a 1-to-1 relation with a row in the `auth.accounts` table.

@MaxSchilling If I understand your use case correctly you want to display "User not active" as an error message if a user tries to log in to an account that is not already active?

That should be available: https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/auth/login.ts#L112-L114

If not, what's the error message you get when trying to log in to an un-active account with this Flutter SDK?

**Comment by MaxSchilling** [comment]
Thanks for the reply! 
You are perfectly right, we are able to catch the message and I now understood that I can do requests on the users table without activated users, thats fine.
I was just afraid that the error message may change easier/faster then a dedicated statuscode or something, somthat we won't risk the chance of catching non existing messages in the future. But a query offers that — got it.

What would perfectly round the auth process up now would be a possibility to re trigger the verification email, but I saw there is a ticket ongoing right now 😊

**Comment by elitan** [comment]
Nice! Resend verification is coming in the coming releases of auth. 

https://github.com/nhost/hasura-backend-plus/pull/524
