### ISSUE TITLE
Broken links in all README.md

### ISSUE THREAD

**Issue by raphaelbarbosaqwerty** [nhost/nhost-dart#3]
Some links are broken in the documentation

**Comment by adithyaakrishna** [comment]
@raphaelbarbosaqwerty Could you tell me which repo has this?😶
Would love to work on it

**Comment by raphaelbarbosaqwerty** [comment]
@adithyaakrishna I made a PR but it didn't pass (strange). I'm closing my PR another guy did the same changes and has passed. my [PR](https://github.com/nhost/nhost-dart/pull/4) the another [PR](https://github.com/nhost/nhost-dart/pull/5)

**Comment by raphaelbarbosaqwerty** [comment]
Issue closed in PR [#4](https://github.com/nhost/nhost-dart/pull/4)
