### ISSUE TITLE
Flutter release apk issue

### ISSUE THREAD

**Issue by krbera** [nhost/nhost-dart#33]
Hi,
I am facing an issue in Nhost flutter application, whenever I am using debug mode apk that time login working properly but in release, app login is not working so can anyone help me?

**Comment by shyndman** [comment]
Hi @krbera,

I can help. Can you provide me with as much detail as you can? Anything that might help.

**Comment by shyndman** [comment]
Closing for lack of response. 

Feel free to comment and I'll open it back up.
