### ISSUE TITLE
Apple login support?

### ISSUE THREAD

**Issue by yevyevyev** [nhost/nhost-dart#34]
Hi. I really love your platform, few points here:

1. On iOS if you include any oauth in your app, it must support apple auth otherwise the app will be rejected.
2. What is the advantage of using webview url redirect over fetching the oauth access token natively like this? https://pub.dev/packages/google_sign_in Can this be supported in nhost sdk?
3. Suggestion - I think there is a win in copying the package API design from firebase, as it becomes the de-facto standart in flutter community for implementing auth. People will have less headache migrating to this platform.

**Comment by shyndman** [comment]
Hi @tapkain,

Thank you!

> 1. On iOS if you include any oauth in your app, it must support apple auth otherwise the app will be rejected.

Ah, interesting. I didn't know that. 

For documentation's sake, this is the relevant section in the App Store Review Guidelines: 

https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple

> 2. What is the advantage of using webview url redirect over fetching the oauth access token natively like this? https://pub.dev/packages/google_sign_in Can this be supported in nhost sdk?

This library was designed to mirror https://github.com/nhost/nhost-js-sdk, and makes use of same backend APIs. Easier to get something off the ground that way.

That said, a more integrated approach like that package you linked is definitely possible at some point. I'll split this request off into its own issue and bring it up with the team.

> 3. Suggestion - I think there is a win in copying the package API design from firebase, as it becomes the de-facto standard in flutter community for implementing auth. People will have less headache migrating to this platform.

Is there anything in particular you find that Nhost is missing, or is it purely a portability concern?

**Comment by tapkain** [comment]
```Is there anything in particular you find that Nhost is missing, or is it purely a portability concern?```
It is purely a portability concern, I personally don't mind about current design

**Comment by PRAJINPRAKASH** [comment]
Its requirement for all app with social logins. https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple

**Comment by dbarrosop** [comment]
this should be fine now. Thanks for reporting.
