### ISSUE TITLE
404 Error when attempting to register a user with nhost_sdk.

### ISSUE THREAD

**Issue by erikmaddy** [nhost/nhost-dart#48]
I followed the [simple auth example](https://github.com/nhost/nhost-dart/blob/main/packages/nhost_sdk/example/lib/auth_example.dart) but when I actually run it and try to register a user, I get this error.

`ApiException(apiUrl=https://*uniqueID*.nhost.run/auth/register, statusCode=404, responseBody={path: $, error: resource does not exist, code: not-found})`

I am assuming it has something to do with me using an Nhost v2 address but I don't see a way of switching to v2 in the SDK.
Thank you in advance.

**Comment by MaxSchilling** [comment]
The dart sdk hasn‘t been updated to v2 yet - but I guess it shouldn‘t take too long any more?

**Comment by shyndman** [comment]
Yes, that's correct.

I'm just waiting on a couple backend inconsistencies to be ironed out. I'll have the new version published soon.

**Comment by erikmaddy** [comment]
Awesome! That seemed to the logical reason. 
I appreciate both of you reaching out.

**Comment by rdeterre** [comment]
Hi. I'm trying to make a new application with a Flutter client, but I can't find where I can select v1 or v2. Is this a setting somewhere on the console?

**Comment by erikmaddy** [comment]
To my knowledge, v1 is being deprecated. You can't create a new v1 project anymore. app.nhost.io is strictly v2. In the v2 public beta announcement, it was mentioned that the flutter SDK will be getting an update very soon.

[v2 announcement blog post](https://www.nhost.io/blog/nhost-v2-the-beginning-of-something-big)

**Comment by shyndman** [comment]
I just published the first set of beta packages for working with Nhost v2. Still a work in progress, but it will tighten up over the coming days:

```
nhost_sdk                3.0.0-beta.0
nhost_gql_links          2.0.0-beta.0
nhost_flutter_auth       2.0.0-beta.0
nhost_graphql_adapter    2.0.0-beta.0
nhost_flutter_graphql    2.0.0-beta.0
```

**Comment by damywise** [comment]
Will there be any breaking changes?
