### ISSUE TITLE
Add support for Nhost v2

### ISSUE THREAD

**Issue by shyndman** [nhost/nhost-dart#51]
Beta is out the door. Work remaining:

* [ ] Evaluate the need for _loading in AuthService
* [x] Add missing sign in methods
* [ ] Review backend endpoint by endpoint, ensuring we have support
  * [x] Resend e-mail verification process/e-mail

**Comment by shyndman** [comment]
Not quite ready to close yet.

**Comment by shyndman** [comment]
Just published #50 to `pub`. Here are the new versions:

```
nhost_sdk                3.0.0-beta.0
nhost_gql_links          2.0.0-beta.0
nhost_flutter_auth       2.0.0-beta.0
nhost_graphql_adapter    2.0.0-beta.0
nhost_flutter_graphql    2.0.0-beta.0
```

This is still a work in progress, but I'm going to be knocking off what's missing over the coming days, and continue to cut beta releases as I do so.

**Comment by shyndman** [comment]
New set of packages out the door, including the changes in #57 and #58.

```
nhost_sdk                3.0.0-beta.1
nhost_gql_links          2.0.0-beta.1
nhost_flutter_auth       2.0.0-beta.1
nhost_graphql_adapter    2.0.0-beta.1
nhost_flutter_graphql    2.0.0-beta.1
```

**Comment by serge-deugoue** [comment]
has version 3 of nhost_sdk been released on pub.dev already?

**Comment by MaxSchilling** [comment]
Hi @shyndman, Johan said that V2 will offer an endpoint to retrieve the e-mail verification process/e-mail, is that already covered within the new sdk as method? Thanks!

**Comment by shyndman** [comment]
Hey @MaxSchilling,

It is not. Let me take a look at getting this in.

**Comment by shyndman** [comment]
To be clear, you're looking to retrieve the text of the verification email?

**Comment by shyndman** [comment]
If you're looking for the ticket used to verify the email address, it's stored in the `auth.users` table, and can be accessed via gql. Keep in mind that the permissions will have to be set up appropriately to modify view/modify the value.

**Comment by MaxSchilling** [comment]
Hey Scott,
no actually a method to re-trigger the actual email-verification mail from the server, as the account activation ticket (that is created on registration) expires after 60 minutes. 
As I understood Johan in V2 there is a way/endpoint to retrigger the token and trigger the activation mail for the user again. This wasn't possible in v1 and we lost quite some users through missing that functionality / not activating within 60 minuted.

So would be great to provide that functionality.

Bonus would be if the authenticationState could reflect wether the user activated the account yet, would make the routing easier to route to a re-send verification screen / functionality.

**Comment by shyndman** [comment]
Got it.

@elitan, which endpoint is @MaxSchilling referring to?

**Comment by elitan** [comment]
@shyndman This one: https://github.com/nhost/nhost/blob/main/packages/hasura-auth-js/src/hasura-auth-api.ts#L149

**Comment by shyndman** [comment]
Thanks! Got that in. 

I'm publishing a new set of packages now. Here are the versions:

```
nhost_sdk                3.0.0-beta.3
nhost_flutter_auth       2.0.0-beta.3
nhost_gql_links          2.0.0-beta.3
nhost_graphql_adapter    2.0.0-beta.3
nhost_flutter_graphql    2.0.0-beta.3
```

**Comment by shyndman** [comment]
Packages are now graduated to stable:

```
nhost_sdk                3.0.0
nhost_gql_links          2.0.0
nhost_graphql_adapter    2.0.0
nhost_flutter_auth       2.0.0
nhost_flutter_graphql    2.0.0
```
