### ISSUE TITLE
Error propagation during refresh instead of silent failure 

### ISSUE THREAD

**Issue by pjindal91** [nhost/nhost-dart#56]
Hi, previously it was discussed [here](https://github.com/nhost/nhost-dart/issues/32#issuecomment-904226626) that there is a design flaw in the library where it doesn't propagate the errors back to the client when exception happens during refresh of token. I am wondering if migration to version 2 is a good opportunity to do that as it might be a breaking change depending on how the library is redesigned.

Example [here](https://github.com/nhost/nhost-dart/blob/main/packages/nhost_sdk/lib/src/auth.dart#L491), the exceptions are logged and not propagated to the client hence the client is eternally in AuthenticationState.inprogress state. In my previous project i overcame this limitation but by putting a time out on the application side but I think this should be fixed in the library. 

If the resdesign of the library is out of scope then one small enhancement we can make is just like we allow clients to add state [change handlers](https://github.com/nhost/nhost-dart/blob/main/packages/nhost_sdk/lib/src/auth.dart#L136), we can allow clients to register error callback handler, which can be called when the above exception happens with appropriate error message. Although its not a full proof solution since the application might not register with the error callback, it will atleast provide a way for the application to know that an exception happened underneath.

Imo correct way would be to decouple initialization of Auth instance with refresh from [here](https://github.com/nhost/nhost-dart/blob/main/packages/nhost_sdk/lib/src/auth.dart#L69). I think we should let the client call a function refreshToken explicitly after they have initialized NhostClient and by extension Auth object. That way we can simply throw the exception from refreshToken function and client can handle it on their side.

What do you think @shyndman? I am happy to work on this fix once we decide which approach to take.

**Comment by shyndman** [comment]
Yeah, this is important.

> Imo correct way would be to decouple initialization of Auth instance with refresh from here. I think we should let the client call a function refreshToken explicitly after they have initialized NhostClient and by extension Auth object. That way we can simply throw the exception from refreshToken function and client can handle it on their side.

It's a good suggestion, but it only handles the initial token refresh.

The first thing `Auth` does after the initial refresh is to set up a timer for the next one. That timer creates the same problem that the constructor does now — failure can't be signaled via exceptions, because we don't have the stack to do it.

So yeah...I _think_ that leaves us with state change handlers.

Like you said, they aren't foolproof, but maybe we could improve the situation by throwing an exception if we fail and the application hasn't provided a handler?

The exception (being timer-invoked) will hit [`Zone.handleUncaughtError`](https://api.flutter.dev/flutter/dart-async/Zone/handleUncaughtError.html), where the application has an opportunity to do something about it. If it doesn't, the exception will print noisily, making it known to the devs that something _should_ be done.

What do you think? Other suggestions?

**Comment by pjindal91** [comment]
Yeah good point about the timer expiry. Keeping that in mind and i think error handler might be a good way to go and will help in this situation. However i think there might be some traps with it. For example a client initialize NhostClient and does some work and by the time they attach  error handler, exception has already happened and later when the add the error handler, its too late. Do you think that could be problematic?

Also more i think about it, more i feel that authentication initialization(which includes refresh token and setting up timer) should be independent from creation of NhostClient initialization. I can think of cases where client still wants to be able retrieve data from graphql/call functions/etc when authentication fails so that can show some restricted version of the application. I feel the fact the problem is two fold:
- The only way to use local stored refresh token is to provide autoLogin which initializing NhostClient
- Failure in refreshToken code path leave us two option, one of which is to blow up the initialization of NhostClient which is not ideal imo, and second is to communicate to the client outside of stack which is by handler

To me the coupling of initialization of auth which includes refresh token workflow and initialization of NhostClient is looking a bit like violation of Single Responsibility Principle. If redesign would be an option, i would be tempted to decouple it by first removing the autoLogin from NhostClient(as it is only specific to auth) and either not initializing auth at all and let the caller init it or init it but not refreshToken and let the client do something like auth.autoLogin() manually.

What are your thoughts? I am totally okay with handling this incrementally and for the time being just providing error handler option and expect the application developer to do things right way.

**Comment by shyndman** [comment]
OK, I buy all of it. Let me get a strawman together.

**Comment by shyndman** [comment]
Ok, I have a version of this out the door:

```
nhost_sdk-v3.0.0-beta.2, 
nhost_graphql_adapter-v2.0.0-beta.2, 
nhost_gql_links-v2.0.0-beta.2, 
nhost_flutter_graphql-v2.0.0-beta.2, 
nhost_flutter_auth-v2.0.0-beta.2
```

Let me know if it work for you.
