### ISSUE TITLE
I/flutter (15918): Exception: type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by MaxSchilling** [nhost/nhost-dart#6]
Registration without auto-activation of new users results in the error.

auth.dart from the package, code doesn't reach line 203 in the auth.dart, which should hopefully handle it right, but the rethrow above blocks that.

**Comment by shyndman** [comment]
Hey @MaxSchilling,

Thanks! I'm taking a look at getting this merged now.

**Comment by shyndman** [comment]
Merged.
