### ISSUE TITLE
Unable to add uploadedByUserId when uploading to nhost.

### ISSUE THREAD

**Issue by Achudh** [nhost/nhost-dart#69]
There are no args to include `userId` to be used in `uploadedByUserId`. There is no way to have userId when uploading in nhost reference and docs.

![Screenshot 2022-06-11 at 11 56 55 AM](https://user-images.githubusercontent.com/18098565/173176158-ba93fbba-a697-4fd7-98bc-a62da1c40f75.png)

**Comment by elitan** [comment]
We'll depricate the `uploadedByUserId` column. See here: https://github.com/nhost/hasura-storage/issues/4

I recommend that you create a separate table where you save the file id and the user id to track who uploaded what.
