### ISSUE TITLE
Custom metadata on signing up

### ISSUE THREAD

**Issue by MichalNemec** [nhost/nhost-dart#74]
Hello,

Would it be possible to modify this query to accept anything to metadata?
https://github.com/nhost/nhost-dart/blob/main/packages/nhost_sdk/lib/src/auth_client.dart#L218

i.e. i have to store location, age, height, ...

**Comment by szilarddoro** [comment]
I'm closing this, because the [latest release](https://pub.dev/packages/nhost_flutter_auth) makes it possible to provide `metadata` to sign up.
