### ISSUE TITLE
loggin user with auth.login just hangs for ever

### ISSUE THREAD

**Issue by seyaobey-dev** [nhost/nhost-dart#8]
So I have setup authentication with `nhost-dart` following the guideline from this repository:
```
final nhostClient = NhostClient(baseUrl: authUrl);
...
Widget build(BuildContext context) {
    return NhostAuthProvider(
      auth: nhostClient!.auth, <---
      child: NhostGraphQLProvider(
        nhostClient: nhostClient,
        ...
```
Now in my `login.screen`, I call `await auth.login(email: __email, password: __password);`
This call just takes for ever (2 to 3 minutes) and then crashes the following exception:

![image](https://user-images.githubusercontent.com/83374925/117588102-a2e6bd80-b121-11eb-84ac-25572b000420.png)

This behavior is not consistent. I would say it happens in 40% of cases.
Thank you for any help on finding a solution.

**Comment by elitan** [comment]
@seyaobey-dev What was the fix for this issue? Might be useful for the next person having the same problem and finds this issue.

**Comment by seyaobey-dev** [comment]
@elitan Before `nhost.io` I was using the normal `flutter_graphql` library, connnected to my custom `nest.js` server. I suspect there was conflict somewhere in my code between the 2 settings, so probably not an issue with `nhost.io`. 
I wanted to delete this issue but there is only the `close` option.
