### ISSUE TITLE
No method to get public file URL from Storage

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost-dart#80]
How to get a public URL if we want to download a file manually without using the functions `storage.downloadFile` or `storage.downloadImage`, Something like [getPublicUrl](https://docs.nhost.io/reference/javascript/storage/get-public-url) in the storage.

At the same time, I tried to use the `getPresignedUrl` from storage with Nhost running from CLI but I'm keep getting an error `ERR_CONNECTION_REFUSED`

Thank You!

**Comment by marcusrohden** [comment]
I'm also with the same issue. I'm trying to get the url to use caching packages such as CachedNetworkImage. In case it is not possible, has anyone found any caching solution for image files? thank you

**Comment by MaxSchilling** [comment]
👀 Following - will need the functionality as well!

**Comment by vipafattal** [comment]
I managed to create `getPublicUrl` function and it's simple.

Looking for the javascript implement for [storage client](https://github.com/nhost/nhost/blob/6ea9ed69ce73b9e0c426d40f20ee42814b21d7cb/packages/hasura-storage-js/src/hasura-storage-client.ts):

```js
 getPublicUrl(params: StorageGetUrlParams): string {
    const { fileId } = params
    return `${this.url}/files/${fileId}`
 }
```

As you can see from the code above, it's as simple as 
```dart
final fileUrl =  "{STORAGE_URL}/files/{FILE_ID}";
```
 Please note to be able to access the file publicly (without being authed user) you need to make a public role with select permission. For me, I made a public role that allows selection only on images `mime_type` just like below
 
 
![image](https://user-images.githubusercontent.com/22567094/188317650-e03fc264-b6a7-40b8-be6e-1ea37f3b45b8.png)

**Comment by kevin4dhd** [comment]
Why is this not implemented in the flutter package? Or maybe it was already implemented but it is under a different name, but this is very important to avoid doing other tricks outside the library

**Comment by kevin4dhd** [comment]
For people looking for a quick fix, for me it was this:

final fileName = '$userId/${DateTime.now().millisecondsSinceEpoch}.jpg';
final fileBytes = await _selectedImage!.readAsBytes();
final response = await nhostClient.storage.uploadBytes(
  fileName: fileName,
  fileContents: fileBytes,
  mimeType: 'image/jpeg',
);
return "https://$subdomain.storage.$region.nhost.run/v1/files/${response.id}";

I don't know if it has an expiration time, but with this I already have the public URL, if the URL expires I will let you know here
