### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by marcusrohden** [nhost/nhost-dart#82]
Hi guys, 
I'm constantly receiving the following exception and logs after the app refreshes the token a couple times.

"Unhandled Exception: Connection closed before full header was received"
"[nhost] Exception during token refresh"
"Connection closed before full header was received".

After the exception occurs, it seems that the Token stop from being refreshed.

![Screen Shot 2022-09-14 at 11 31 53 pm](https://user-images.githubusercontent.com/8283160/190167829-7d8d882d-2164-4fdf-b3bf-ca4e5e19b26f.png)

**Comment by MichalNemec** [comment]
do you have local development of nhost? maybe you would see more information.
