### ISSUE TITLE
Subscriptions are failing to update

### ISSUE THREAD

**Issue by shyndman** [nhost/nhost-dart#9]
This was originally reported by @escamoteur via Discord.

After running the software, leaving it for a bit and coming back, subscriptions were no longer updating.

This has been reported as happening on Windows, and macOS.

**Comment by shyndman** [comment]
I have been unable to reproduce on macOS, using the same app that Thomas is working on. I'm getting my Windows machine setup to see if I can repro there.

**Comment by seyaobey-dev** [comment]
I'm having the same problem; I'm on macos. Subscriptions updates are not consistent. They ran a couple of time and then just stopped updating. Sometimes they update after much time (3 to 5 min after the mutation has been executed). Here is my code:
```
  @override
  void initState() {
    super.initState();

    final subscription = client.subscribe(SubscriptionOptions(document: gql(r'''
        subscription members {
          members {
            id
          }
        }
      ''')));

    subscription.listen((res) {
      if (res.data != null) {
        print("${res.data}"); // <-- this is inconsistent
      }
    });
  }
```

**Comment by shyndman** [comment]
Thanks @seyaobey-dev. 

Is the mutation also taking place via the same app? I'd like to build something as close as I can to attempt a repro.

**Comment by shyndman** [comment]
I found the bug. I'm working out a fix now.

**Comment by shyndman** [comment]
I reported my findings to `graphql`, but I'm preparing an interim fix. I'll be pushing it soon.

**Comment by shyndman** [comment]
I published a number of pre-release versions that should fix the issue. I'll be promoting them to a stable version soon.

```
nhost_flutter_auth    1.0.3-dev.1 
nhost_flutter_graphql 1.0.3-dev.1 
nhost_gql_links       1.0.1-dev.2 
nhost_graphql_adapter 1.0.3-dev.2 
nhost_sdk             1.0.3-dev.1 
```

**Comment by shyndman** [comment]
Still not quite there, but I'm focused on it.

**Comment by shyndman** [comment]
Yes, OK, so the prereleases I mentioned earlier do not work. I misunderstood what my test harness was reporting.

But I have found the issue (I'm not disconnecting the socket properly), and I'll have something up by EOD. Thanks for your patience.

**Comment by shyndman** [comment]
Hey folks,

I've pushed a new set of pre-release versions that are creeping towards stability. While I still anticipate issues after some of the problems I've observed in the link libraries, I have an _early_ _early_ report from @MaxSchilling suggesting that he is no longer encountering issues with subscriptions, after multiple token refreshes.

I also sent a PR over to the `graphql` repo to include stack traces in more of the exception they emit...because when these exceptions do happen, their source can be next to impossible to determine. Hopefully that will be accepted.

@escamoteur, unfortunately, this does not yet resolve issues with Donation Tracker. I'm going to have to do more link surgery to figure out what's happening there.

```
nhost_flutter_auth    1.0.3-dev.2 
nhost_flutter_graphql 1.0.3-dev.2 
nhost_gql_links       1.0.1-dev.4 
nhost_graphql_adapter 1.0.3-dev.4 
nhost_sdk             1.0.3-dev.2 
```

**Comment by shyndman** [comment]
OK, @escamoteur's issues were unrelated, and https://github.com/gql-dart/gql/issues/227, while problematic, isn't blocking, so we are now published as stable. 

```
nhost_flutter_auth    1.0.3
nhost_flutter_graphql 1.0.3
nhost_gql_links       1.0.2
nhost_graphql_adapter 1.0.4
nhost_sdk             1.0.3
```

Please post back to this bug if there are any problems.
