### ISSUE TITLE
Need keep login status even when APP reopen

### ISSUE THREAD

**Issue by bigzhu** [nhost/nhost-dart#91]
When APP reopen, always need login, it's so silly.

**Comment by marcusrohden** [comment]
You can easily do that by managing the auth status with the Nhost Auth callback to update your app state.

```
<Your nhost client>.auth
        .addAuthStateChangedCallback((authenticationState) {
      log('AUTH STATUS CHANGED: ${authenticationState.name}');
      _updateLoginStatus();
    });
```

**Comment by mhadaily** [comment]
You can use the `.signInWithStoredCredentials()` method on the initial load to ensure the user can log in. Please make sure to catch an error, as this method throw an exception if a silent log in is not possible. 

```
nhostClient.auth
        .signInWithStoredCredentials()
        .then((value) {print('user is signed in $value'})
        .catchError(print);
````
