### ISSUE TITLE
Using `Storage.uploadBytes` to upload file result `uploadedByUserId` is always null  

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost-dart#99]

**Comment by mhadaily** [comment]
I am sorry I didn't understand, the `uploadBytes` should return `Future<FileMetadata>` ?

**Comment by vipafattal** [comment]
Sorry, I didn't mean on the front end but on the backend, the column `upload_by_user_id` in the `files` table is always null

**Comment by mhadaily** [comment]
Then, this is not related to Dart SDK, however, I will try to reproduce and report it back to the team.

**Comment by dbarrosop** [comment]
No, that field was deprecated long ago so this is intended. There was some discussion an alternative solutions [here](https://github.com/nhost/hasura-storage/issues/4).
